# Form implementation generated from reading ui file 'D:\DTB\uel\HK1\tu duy lap trinh\DuongThanhBinh_K244060766_Module28\DoAnCuoiKi\Ui\ui_BiaChinh\bia.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1100, 700))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_BiaChinh\\../../Images/Images_BiaChinh/bia.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 120, 531, 581))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_BiaChinh\\../../Images/Images_BiaChinh/cho.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.labelHotline = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelHotline.setGeometry(QtCore.QRect(480, 20, 211, 41))
        self.labelHotline.setStyleSheet("font: 15pt \"Segoe UI Variable Text\";\n"
"")
        self.labelHotline.setObjectName("labelHotline")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(760, 10, 41, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_BiaChinh\\../../Images/Images_BiaChinh/ic_web.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 10, 41, 41))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_BiaChinh\\../../Images/Images_BiaChinh/ic_web.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(430, 10, 41, 41))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_BiaChinh\\../../Images/Images_BiaChinh/ic_phone.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(60, 620, 431, 41))
        self.label_12.setStyleSheet("\n"
"font: 15pt \"Bahnschrift SemiLight SemiConde\";\n"
"color: rgb(115, 115, 115);\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 620, 31, 31))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_BiaChinh\\../../Images/Images_BiaChinh/ic_location_red.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.pushButtonDatLich = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDatLich.setGeometry(QtCore.QRect(70, 460, 191, 41))
        self.pushButtonDatLich.setStyleSheet("QPushButton {\n"
"    background-color: #fae38c; \n"
"    border-radius: 20px;       \n"
"    color: black;               \n"
"    padding: 5px 10px;        \n"
"    font: 14pt \"Sitka Display\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 217, 102, 100); \n"
"}\n"
"")
        self.pushButtonDatLich.setObjectName("pushButtonDatLich")
        self.pushButtonDangNhap = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDangNhap.setGeometry(QtCore.QRect(300, 460, 191, 41))
        self.pushButtonDangNhap.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid #fee286;  /* Viền vàng */\n"
"    border-radius: 20px;  /* Bo tròn góc */\n"
"    color: black;  /* Màu chữ */\n"
"    font: 14pt \"Sitka Display\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 217, 102, 50); /* Hiệu ứng hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 217, 102, 100);\n"
"}\n"
"\n"
"")
        self.pushButtonDangNhap.setObjectName("pushButtonDangNhap")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(0, 90, 131, 81))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_BiaChinh\\../../Images/Images_BiaChinh/logo.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(100, 100, 101, 41))
        self.label_15.setStyleSheet("font: 15pt \"Bahnschrift SemiLight SemiConde\";\n"
"color: rgb(115, 115, 115);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(100, 120, 101, 41))
        self.label_16.setStyleSheet("font: 15pt \"Bahnschrift SemiLight SemiConde\";\n"
"color: rgb(115, 115, 115);")
        self.label_16.setObjectName("label_16")
        self.labelWebsite_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelWebsite_2.setGeometry(QtCore.QRect(90, 20, 211, 41))
        self.labelWebsite_2.setStyleSheet("font: 15pt \"Segoe UI Variable Text\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.labelWebsite_2.setObjectName("labelWebsite_2")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 0, 101, 41))
        self.label_7.setStyleSheet("font: 15pt \"Bahnschrift SemiLight SemiConde\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 0, 81, 41))
        self.label_5.setStyleSheet("font: 16pt \"Bahnschrift SemiLight SemiConde\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(810, 0, 101, 41))
        self.label_6.setStyleSheet("font: 16pt \"Bahnschrift SemiLight SemiConde\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(810, 20, 241, 41))
        self.label_9.setStyleSheet("font: 15pt \"Segoe UI Variable Text\";\n"
"")
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelHotline.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:696; color:#000000;\">0968 686 868 </span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Số 86, khu phố 6, phường Linh Xuân, TP Thủ Đức"))
        self.pushButtonDatLich.setText(_translate("MainWindow", "ĐẶT LỊCH HẸN NGAY"))
        self.pushButtonDangNhap.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.label_15.setText(_translate("MainWindow", "HEALTHY "))
        self.label_16.setText(_translate("MainWindow", "PETS"))
        self.labelWebsite_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">www.drpethouse.com</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Website"))
        self.label_5.setText(_translate("MainWindow", "Hotline"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:696; color:#000000;\">drpethouse@gmail.com</span></p></body></html>"))
