# Form implementation generated from reading ui file 'C:\Users\Kieu Tien\DoAnCuoiKy\DoAnCuoiKi\Ui\ui_QuanLyLichHen\QuanLyLichHen.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        MainWindow.setMaximumSize(QtCore.QSize(1100, 700))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1100, 700))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/qllh.png"))
        self.label.setObjectName("label")
        self.labelTenKhachHang = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTenKhachHang.setGeometry(QtCore.QRect(70, 10, 191, 51))
        self.labelTenKhachHang.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Sitka Display\";\n"
"background: transparent; /* Nền trong suốt */    ")
        self.labelTenKhachHang.setObjectName("labelTenKhachHang")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(330, 20, 391, 61))
        self.label_10.setStyleSheet("background-color: rgb(52, 76, 183);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px; ")
        self.label_10.setObjectName("label_10")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 1081, 331))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabLichHen = QtWidgets.QWidget()
        self.tabLichHen.setObjectName("tabLichHen")
        self.tableWidgetThongTinLH = QtWidgets.QTableWidget(parent=self.tabLichHen)
        self.tableWidgetThongTinLH.setGeometry(QtCore.QRect(0, 50, 1071, 251))
        self.tableWidgetThongTinLH.setStyleSheet("font: 75 10pt \"Sitka Display\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tableWidgetThongTinLH.setObjectName("tableWidgetThongTinLH")
        self.tableWidgetThongTinLH.setColumnCount(8)
        self.tableWidgetThongTinLH.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinLH.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinLH.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinLH.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinLH.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinLH.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(7, item)
        self.pushButtonDaXacNhan = QtWidgets.QPushButton(parent=self.tabLichHen)
        self.pushButtonDaXacNhan.setGeometry(QtCore.QRect(360, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonDaXacNhan.setFont(font)
        self.pushButtonDaXacNhan.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-bottom: 2px solid black; \n"
"    \n"
"    background-color: rgb(153, 225, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(39, 154, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(153, 225, 255);\n"
"}")
        self.pushButtonDaXacNhan.setObjectName("pushButtonDaXacNhan")
        self.pushButtonHienThiTatCaLH = QtWidgets.QPushButton(parent=self.tabLichHen)
        self.pushButtonHienThiTatCaLH.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonHienThiTatCaLH.setFont(font)
        self.pushButtonHienThiTatCaLH.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #fae38c; \n"
"    border: none; /* Xóa viền */\n"
"    border-bottom: 2px solid black; /* Gạch dưới */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fae38c;\n"
"}\n"
"\n"
"")
        self.pushButtonHienThiTatCaLH.setObjectName("pushButtonHienThiTatCaLH")
        self.pushButtonChuaXacNhan = QtWidgets.QPushButton(parent=self.tabLichHen)
        self.pushButtonChuaXacNhan.setGeometry(QtCore.QRect(500, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonChuaXacNhan.setFont(font)
        self.pushButtonChuaXacNhan.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-bottom: 1.5px solid black; \n"
"    background-color: rgb(255, 108, 98);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(255, 25, 48);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 108, 98);\n"
"}")
        self.pushButtonChuaXacNhan.setObjectName("pushButtonChuaXacNhan")
        self.pushButtonThemLH = QtWidgets.QPushButton(parent=self.tabLichHen)
        self.pushButtonThemLH.setGeometry(QtCore.QRect(160, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonThemLH.setFont(font)
        self.pushButtonThemLH.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #fae38c; \n"
"    border: none; /* Xóa viền */\n"
"    border-bottom: 2px solid black; /* Gạch dưới */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fae38c;\n"
"}\n"
"\n"
"")
        self.pushButtonThemLH.setIconSize(QtCore.QSize(30, 20))
        self.pushButtonThemLH.setObjectName("pushButtonThemLH")
        self.lineEditTimKiem = QtWidgets.QLineEdit(parent=self.tabLichHen)
        self.lineEditTimKiem.setGeometry(QtCore.QRect(730, 10, 251, 31))
        self.lineEditTimKiem.setStyleSheet("QLineEdit {\n"
"    border:1px solid#00007f ;\n"
"    color: rgb(0, 0, 127);\n"
"    border-radius: 15px;        \n"
"    font: 13pt \"MS Shell Dlg 2\";\n"
"    background-color: #fbf9f8;     \n"
"    padding-left: 10px; \n"
"    padding-right: 20px;        \n"
"}")
        self.lineEditTimKiem.setObjectName("lineEditTimKiem")
        self.pushButtonTimKiem = QtWidgets.QPushButton(parent=self.tabLichHen)
        self.pushButtonTimKiem.setGeometry(QtCore.QRect(940, 10, 31, 31))
        self.pushButtonTimKiem.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;                     \n"
"    padding: 5px 10px;        \n"
"    text-decoration: underline;\n"
"    background-color:None;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(208, 209, 208);\n"
"}\n"
"")
        self.pushButtonTimKiem.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/search.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonTimKiem.setIcon(icon)
        self.pushButtonTimKiem.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonTimKiem.setObjectName("pushButtonTimKiem")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/hen.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tabLichHen, icon1, "")
        self.tabDaKham = QtWidgets.QWidget()
        self.tabDaKham.setObjectName("tabDaKham")
        self.tableWidgetThongTinDK = QtWidgets.QTableWidget(parent=self.tabDaKham)
        self.tableWidgetThongTinDK.setGeometry(QtCore.QRect(0, 50, 1071, 251))
        self.tableWidgetThongTinDK.setMaximumSize(QtCore.QSize(1071, 16777215))
        self.tableWidgetThongTinDK.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tableWidgetThongTinDK.setObjectName("tableWidgetThongTinDK")
        self.tableWidgetThongTinDK.setColumnCount(8)
        self.tableWidgetThongTinDK.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinDK.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinDK.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinDK.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinDK.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinDK.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(7, item)
        self.pushButtonHienThiTatCaDK = QtWidgets.QPushButton(parent=self.tabDaKham)
        self.pushButtonHienThiTatCaDK.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonHienThiTatCaDK.setFont(font)
        self.pushButtonHienThiTatCaDK.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #fae38c; \n"
"    border: none; /* Xóa viền */\n"
"    border-bottom: 2px solid black; /* Gạch dưới */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fae38c;\n"
"}\n"
"\n"
"")
        self.pushButtonHienThiTatCaDK.setObjectName("pushButtonHienThiTatCaDK")
        self.lineEditTimKiem_2 = QtWidgets.QLineEdit(parent=self.tabDaKham)
        self.lineEditTimKiem_2.setGeometry(QtCore.QRect(700, 10, 251, 31))
        self.lineEditTimKiem_2.setStyleSheet("QLineEdit {\n"
"    border:1px solid#00007f ;\n"
"    color: rgb(0, 0, 127);\n"
"    border-radius: 15px;        \n"
"    font: 13pt \"MS Shell Dlg 2\";\n"
"    background-color: #fbf9f8;     \n"
"    padding-left: 10px; \n"
"    padding-right: 20px;        \n"
"}")
        self.lineEditTimKiem_2.setObjectName("lineEditTimKiem_2")
        self.pushButtonTimKiem_2 = QtWidgets.QPushButton(parent=self.tabDaKham)
        self.pushButtonTimKiem_2.setGeometry(QtCore.QRect(910, 10, 31, 31))
        self.pushButtonTimKiem_2.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;                     \n"
"    padding: 5px 10px;        \n"
"    text-decoration: underline;\n"
"    background-color:None;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(208, 209, 208);\n"
"}\n"
"")
        self.pushButtonTimKiem_2.setText("")
        self.pushButtonTimKiem_2.setIcon(icon)
        self.pushButtonTimKiem_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonTimKiem_2.setObjectName("pushButtonTimKiem_2")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/dakham (2).ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tabDaKham, icon2, "")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 420, 410, 232))
        self.groupBox_2.setMaximumSize(QtCore.QSize(410, 232))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Sitka Display\";\n"
"border-radius:10px;\n"
"border: 0.5px solid black;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 75 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px white;")
        self.label_3.setObjectName("label_3")
        self.lineEditKhachHang = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditKhachHang.setGeometry(QtCore.QRect(140, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditKhachHang.setFont(font)
        self.lineEditKhachHang.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.lineEditKhachHang.setObjectName("lineEditKhachHang")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 75 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 140, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font: 75 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("font: 75 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_11.setObjectName("label_11")
        self.lineEditSoDienThoaiKH = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditSoDienThoaiKH.setGeometry(QtCore.QRect(140, 50, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditSoDienThoaiKH.setFont(font)
        self.lineEditSoDienThoaiKH.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}\n"
"")
        self.lineEditSoDienThoaiKH.setObjectName("lineEditSoDienThoaiKH")
        self.lineEditNgayHen = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditNgayHen.setGeometry(QtCore.QRect(140, 90, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditNgayHen.setFont(font)
        self.lineEditNgayHen.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.lineEditNgayHen.setObjectName("lineEditNgayHen")
        self.lineEditGio = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditGio.setGeometry(QtCore.QRect(140, 130, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditGio.setFont(font)
        self.lineEditGio.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.lineEditGio.setObjectName("lineEditGio")
        self.pushButtonLuu = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonLuu.setGeometry(QtCore.QRect(40, 180, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonLuu.setFont(font)
        self.pushButtonLuu.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 16pt \"Sitka Display\";\n"
"    border: 1px solid black;\n"
"    background-color: #fae38c; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #eeba4a;\n"
"}")
        self.pushButtonLuu.setObjectName("pushButtonLuu")
        self.pushButtonXoa = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonXoa.setGeometry(QtCore.QRect(220, 180, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonXoa.setFont(font)
        self.pushButtonXoa.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 16pt \"Sitka Display\";\n"
"    border: 1px solid black;\n"
"    background-color: #fae38c; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #eeba4a;\n"
"}")
        self.pushButtonXoa.setObjectName("pushButtonXoa")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(700, 440, 391, 150))
        self.groupBox_3.setMaximumSize(QtCore.QSize(410, 150))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Sitka Display\";\n"
"border-radius:10px;\n"
"border: 0.5px solid black;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 75 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px white;")
        self.label_5.setObjectName("label_5")
        self.lineEditBacSi = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEditBacSi.setGeometry(QtCore.QRect(130, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditBacSi.setFont(font)
        self.lineEditBacSi.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.lineEditBacSi.setObjectName("lineEditBacSi")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 75 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font: 75 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_13.setObjectName("label_13")
        self.lineEditNoiLamViec = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEditNoiLamViec.setGeometry(QtCore.QRect(130, 50, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditNoiLamViec.setFont(font)
        self.lineEditNoiLamViec.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.lineEditNoiLamViec.setObjectName("lineEditNoiLamViec")
        self.lineEditSoDienThoaiBS = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEditSoDienThoaiBS.setGeometry(QtCore.QRect(130, 90, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditSoDienThoaiBS.setFont(font)
        self.lineEditSoDienThoaiBS.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.lineEditSoDienThoaiBS.setObjectName("lineEditSoDienThoaiBS")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 440, 241, 150))
        self.groupBox_4.setMaximumSize(QtCore.QSize(410, 150))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Sitka Display\";\n"
"border-radius:10px;\n"
"border: 0.5px solid black;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButtonDaXacNhan = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButtonDaXacNhan.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.radioButtonDaXacNhan.setStyleSheet("font: 75 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);\n"
"border: none; /* Xóa viền */\n"
"    background: transparent; /* Nền trong suốt */")
        self.radioButtonDaXacNhan.setObjectName("radioButtonDaXacNhan")
        self.radioButtonChuaXacNhan = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButtonChuaXacNhan.setGeometry(QtCore.QRect(20, 60, 171, 31))
        self.radioButtonChuaXacNhan.setStyleSheet("font: 75 14pt \"Sitka Display\";\n"
"color: rgb(255, 64, 64);\n"
"color: rgb(0, 0, 0);\n"
"border: none; /* Xóa viền */\n"
"    background: transparent; /* Nền trong suốt */")
        self.radioButtonChuaXacNhan.setObjectName("radioButtonChuaXacNhan")
        self.radioButtonDaKham = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButtonDaKham.setGeometry(QtCore.QRect(20, 100, 181, 31))
        self.radioButtonDaKham.setStyleSheet("font: 75 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);\n"
"border: none; /* Xóa viền */\n"
"    background: transparent; /* Nền trong suốt */")
        self.radioButtonDaKham.setObjectName("radioButtonDaKham")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuSystem = QtWidgets.QMenu(parent=self.menuBar)
        self.menuSystem.setObjectName("menuSystem")
        self.menuImport_Data = QtWidgets.QMenu(parent=self.menuSystem)
        self.menuImport_Data.setObjectName("menuImport_Data")
        self.menuExport_Data = QtWidgets.QMenu(parent=self.menuSystem)
        self.menuExport_Data.setObjectName("menuExport_Data")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../images/619539_close_delete_dismiss_exit_cancel_icon (2).ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionText_File = QtGui.QAction(parent=MainWindow)
        self.actionText_File.setObjectName("actionText_File")
        self.actionCSV_File = QtGui.QAction(parent=MainWindow)
        self.actionCSV_File.setObjectName("actionCSV_File")
        self.actionXML_File = QtGui.QAction(parent=MainWindow)
        self.actionXML_File.setObjectName("actionXML_File")
        self.actionJSon_File = QtGui.QAction(parent=MainWindow)
        self.actionJSon_File.setObjectName("actionJSon_File")
        self.actionExcel_File_Import = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../images/2993694_brand_brands_excel_logo_logos_icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExcel_File_Import.setIcon(icon4)
        self.actionExcel_File_Import.setObjectName("actionExcel_File_Import")
        self.actionPickle_File = QtGui.QAction(parent=MainWindow)
        self.actionPickle_File.setObjectName("actionPickle_File")
        self.actionTxt_File = QtGui.QAction(parent=MainWindow)
        self.actionTxt_File.setObjectName("actionTxt_File")
        self.actionCSV_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionCSV_File_2.setObjectName("actionCSV_File_2")
        self.actionJSon_FIle = QtGui.QAction(parent=MainWindow)
        self.actionJSon_FIle.setObjectName("actionJSon_FIle")
        self.actionJSON_File = QtGui.QAction(parent=MainWindow)
        self.actionJSON_File.setObjectName("actionJSON_File")
        self.actionExcel_FIle_Export = QtGui.QAction(parent=MainWindow)
        self.actionExcel_FIle_Export.setIcon(icon4)
        self.actionExcel_FIle_Export.setObjectName("actionExcel_FIle_Export")
        self.actionPickle_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionPickle_File_2.setObjectName("actionPickle_File_2")
        self.menuImport_Data.addAction(self.actionText_File)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionCSV_File)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionXML_File)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionJSon_File)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionExcel_File_Import)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionPickle_File)
        self.menuExport_Data.addAction(self.actionTxt_File)
        self.menuExport_Data.addSeparator()
        self.menuExport_Data.addAction(self.actionCSV_File_2)
        self.menuExport_Data.addSeparator()
        self.menuExport_Data.addAction(self.actionJSon_FIle)
        self.menuExport_Data.addSeparator()
        self.menuExport_Data.addAction(self.actionJSON_File)
        self.menuExport_Data.addSeparator()
        self.menuExport_Data.addAction(self.actionExcel_FIle_Export)
        self.menuExport_Data.addSeparator()
        self.menuExport_Data.addAction(self.actionPickle_File_2)
        self.menuSystem.addAction(self.menuImport_Data.menuAction())
        self.menuSystem.addAction(self.menuExport_Data.menuAction())
        self.menuSystem.addAction(self.actionExit)
        self.menuBar.addAction(self.menuSystem.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditTimKiem, self.pushButtonTimKiem)
        MainWindow.setTabOrder(self.pushButtonTimKiem, self.lineEditKhachHang)
        MainWindow.setTabOrder(self.lineEditKhachHang, self.lineEditSoDienThoaiKH)
        MainWindow.setTabOrder(self.lineEditSoDienThoaiKH, self.lineEditNgayHen)
        MainWindow.setTabOrder(self.lineEditNgayHen, self.lineEditGio)
        MainWindow.setTabOrder(self.lineEditGio, self.lineEditBacSi)
        MainWindow.setTabOrder(self.lineEditBacSi, self.lineEditNoiLamViec)
        MainWindow.setTabOrder(self.lineEditNoiLamViec, self.lineEditSoDienThoaiBS)
        MainWindow.setTabOrder(self.lineEditSoDienThoaiBS, self.radioButtonDaXacNhan)
        MainWindow.setTabOrder(self.radioButtonDaXacNhan, self.radioButtonChuaXacNhan)
        MainWindow.setTabOrder(self.radioButtonChuaXacNhan, self.radioButtonDaKham)
        MainWindow.setTabOrder(self.radioButtonDaKham, self.pushButtonLuu)
        MainWindow.setTabOrder(self.pushButtonLuu, self.pushButtonXoa)
        MainWindow.setTabOrder(self.pushButtonXoa, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.pushButtonDaXacNhan)
        MainWindow.setTabOrder(self.pushButtonDaXacNhan, self.pushButtonChuaXacNhan)
        MainWindow.setTabOrder(self.pushButtonChuaXacNhan, self.pushButtonHienThiTatCaLH)
        MainWindow.setTabOrder(self.pushButtonHienThiTatCaLH, self.pushButtonThemLH)
        MainWindow.setTabOrder(self.pushButtonThemLH, self.tableWidgetThongTinLH)
        MainWindow.setTabOrder(self.tableWidgetThongTinLH, self.pushButtonHienThiTatCaDK)
        MainWindow.setTabOrder(self.pushButtonHienThiTatCaDK, self.tableWidgetThongTinDK)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quản lý lịch hẹn - Admin"))
        self.labelTenKhachHang.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#577bc1;\">Tên Khách Hàng</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Quản Lý Lịch Hẹn</span></p></body></html>"))
        item = self.tableWidgetThongTinLH.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetThongTinLH.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetThongTinLH.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetThongTinLH.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetThongTinLH.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Họ & Tên"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Số Điện Thoại"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ngày Khám"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ngày khám"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Bác Sĩ Phụ Trách"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Dịch Vụ"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Nơi Khám"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Tình Trạng"))
        self.pushButtonDaXacNhan.setText(_translate("MainWindow", "Đã Xác Nhận"))
        self.pushButtonHienThiTatCaLH.setText(_translate("MainWindow", "Hiển Thị Tất Cả"))
        self.pushButtonChuaXacNhan.setText(_translate("MainWindow", "Chưa Xác Nhận"))
        self.pushButtonThemLH.setText(_translate("MainWindow", "Thêm Lịch"))
        self.lineEditTimKiem.setPlaceholderText(_translate("MainWindow", "Tìm kiếm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLichHen), _translate("MainWindow", "Lịch Hẹn"))
        item = self.tableWidgetThongTinDK.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetThongTinDK.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetThongTinDK.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetThongTinDK.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetThongTinDK.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Họ & Tên"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Số Điện Thoại"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ngày Khám"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ngày khám"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Bác Sĩ Phụ Trách"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Dịch Vụ"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Nơi Khám"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Tình Trạng"))
        self.pushButtonHienThiTatCaDK.setText(_translate("MainWindow", "Hiển thị tất cả"))
        self.lineEditTimKiem_2.setPlaceholderText(_translate("MainWindow", "Tìm kiếm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDaKham), _translate("MainWindow", "Đã Khám"))
        self.label_3.setText(_translate("MainWindow", "Khách Hàng:"))
        self.label_4.setText(_translate("MainWindow", "Ngày Hẹn:"))
        self.label_9.setText(_translate("MainWindow", "Giờ:"))
        self.label_11.setText(_translate("MainWindow", "Số Điện Thoại:"))
        self.pushButtonLuu.setText(_translate("MainWindow", "Lưu"))
        self.pushButtonXoa.setText(_translate("MainWindow", "Xóa"))
        self.label_5.setText(_translate("MainWindow", "Bác sĩ:"))
        self.label_6.setText(_translate("MainWindow", "Số Điện Thoại:"))
        self.label_13.setText(_translate("MainWindow", "Nơi Làm Việc:"))
        self.radioButtonDaXacNhan.setText(_translate("MainWindow", "Đã Xác Nhận"))
        self.radioButtonChuaXacNhan.setText(_translate("MainWindow", "Chưa Xác Nhận"))
        self.radioButtonDaKham.setText(_translate("MainWindow", "Đã Khám"))
        self.menuSystem.setTitle(_translate("MainWindow", "Cài Đặt"))
        self.menuImport_Data.setTitle(_translate("MainWindow", "Nhập Dữ Liệu"))
        self.menuExport_Data.setTitle(_translate("MainWindow", "Xuất Dữ Liệu"))
        self.actionExit.setText(_translate("MainWindow", "Đăng Xuất"))
        self.actionText_File.setText(_translate("MainWindow", "Text File"))
        self.actionCSV_File.setText(_translate("MainWindow", "CSV File"))
        self.actionXML_File.setText(_translate("MainWindow", "XML File"))
        self.actionJSon_File.setText(_translate("MainWindow", "JSON File"))
        self.actionExcel_File_Import.setText(_translate("MainWindow", "Excel File"))
        self.actionPickle_File.setText(_translate("MainWindow", "Pickle File"))
        self.actionTxt_File.setText(_translate("MainWindow", "Txt File"))
        self.actionCSV_File_2.setText(_translate("MainWindow", "CSV File"))
        self.actionJSon_FIle.setText(_translate("MainWindow", "XML FIle"))
        self.actionJSON_File.setText(_translate("MainWindow", "JSON File"))
        self.actionExcel_FIle_Export.setText(_translate("MainWindow", "Excel FIle"))
        self.actionPickle_File_2.setText(_translate("MainWindow", "Pickle File"))
