# Form implementation generated from reading ui file 'C:\Users\Kieu Tien\DoAnCuoiKy\DoAnCuoiKi\Ui\ui_QuanLyLichHen\QuanLyLichHen.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        MainWindow.setMaximumSize(QtCore.QSize(1100, 900))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -1, 1101, 701))
        self.stackedWidget.setTabletTracking(False)
        self.stackedWidget.setToolTip("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 430, 410, 232))
        self.groupBox_2.setMaximumSize(QtCore.QSize(410, 232))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Sitka Display\";\n"
"border-radius:10px;\n"
"border: 0.5px solid black;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_10.setObjectName("label_10")
        self.lineEditKhachHang = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditKhachHang.setGeometry(QtCore.QRect(140, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditKhachHang.setFont(font)
        self.lineEditKhachHang.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.lineEditKhachHang.setObjectName("lineEditKhachHang")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(20, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 140, 51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_13.setObjectName("label_13")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(20, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_18.setObjectName("label_18")
        self.lineEditSoDienThoaiKH = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditSoDienThoaiKH.setGeometry(QtCore.QRect(140, 50, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditSoDienThoaiKH.setFont(font)
        self.lineEditSoDienThoaiKH.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}\n"
"")
        self.lineEditSoDienThoaiKH.setObjectName("lineEditSoDienThoaiKH")
        self.pushButtonLuu = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonLuu.setGeometry(QtCore.QRect(40, 180, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonLuu.setFont(font)
        self.pushButtonLuu.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 16pt \"Sitka Display\";\n"
"    border: 1px solid black;\n"
"    background-color: #fae38c; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #eeba4a;\n"
"}")
        self.pushButtonLuu.setObjectName("pushButtonLuu")
        self.pushButtonXoa = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonXoa.setGeometry(QtCore.QRect(220, 180, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonXoa.setFont(font)
        self.pushButtonXoa.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 16pt \"Sitka Display\";\n"
"    border: 1px solid black;\n"
"    background-color: #fae38c; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #eeba4a;\n"
"}")
        self.pushButtonXoa.setObjectName("pushButtonXoa")
        self.comboBoxNgayHen = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBoxNgayHen.setGeometry(QtCore.QRect(140, 100, 251, 22))
        self.comboBoxNgayHen.setStyleSheet("\n"
"QComboBox {\n"
"    border: none;\n"
"    border-bottom: 1px solid black; \n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    background: transparent;\n"
"    border-radius: 0px;\n"
"}")
        self.comboBoxNgayHen.setObjectName("comboBoxNgayHen")
        self.comboBoxGio = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBoxGio.setGeometry(QtCore.QRect(140, 140, 251, 22))
        self.comboBoxGio.setStyleSheet("QComboBox {\n"
"    border: none;\n"
"    border-bottom: 1px solid black; \n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    background: transparent;\n"
"    border-radius: 0px;\n"
"}")
        self.comboBoxGio.setObjectName("comboBoxGio")
        self.groupBoxTinhTrang = QtWidgets.QGroupBox(parent=self.page)
        self.groupBoxTinhTrang.setGeometry(QtCore.QRect(460, 430, 191, 131))
        self.groupBoxTinhTrang.setMaximumSize(QtCore.QSize(410, 150))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBoxTinhTrang.setFont(font)
        self.groupBoxTinhTrang.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Sitka Display\";\n"
"border-radius:10px;\n"
"border: 0.5px solid black;")
        self.groupBoxTinhTrang.setTitle("")
        self.groupBoxTinhTrang.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBoxTinhTrang.setObjectName("groupBoxTinhTrang")
        self.radioButtonDaXacNhan = QtWidgets.QRadioButton(parent=self.groupBoxTinhTrang)
        self.radioButtonDaXacNhan.setGeometry(QtCore.QRect(20, 10, 151, 31))
        self.radioButtonDaXacNhan.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.radioButtonDaXacNhan.setObjectName("radioButtonDaXacNhan")
        self.radioButtonChuaXacNhan = QtWidgets.QRadioButton(parent=self.groupBoxTinhTrang)
        self.radioButtonChuaXacNhan.setGeometry(QtCore.QRect(20, 50, 161, 31))
        self.radioButtonChuaXacNhan.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;\n"
"")
        self.radioButtonChuaXacNhan.setObjectName("radioButtonChuaXacNhan")
        self.radioButtonDaKham = QtWidgets.QRadioButton(parent=self.groupBoxTinhTrang)
        self.radioButtonDaKham.setGeometry(QtCore.QRect(20, 90, 161, 31))
        self.radioButtonDaKham.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.radioButtonDaKham.setObjectName("radioButtonDaKham")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.page)
        self.groupBox_6.setGeometry(QtCore.QRect(460, 570, 191, 91))
        self.groupBox_6.setMaximumSize(QtCore.QSize(410, 150))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Sitka Display\";\n"
"border-radius:10px;\n"
"border: 0.5px solid black;")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.radioButtonKhamTaiGia = QtWidgets.QRadioButton(parent=self.groupBox_6)
        self.radioButtonKhamTaiGia.setGeometry(QtCore.QRect(20, 10, 151, 31))
        self.radioButtonKhamTaiGia.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;\n"
"")
        self.radioButtonKhamTaiGia.setObjectName("radioButtonKhamTaiGia")
        self.radioButtonPhongKham = QtWidgets.QRadioButton(parent=self.groupBox_6)
        self.radioButtonPhongKham.setGeometry(QtCore.QRect(20, 50, 161, 31))
        self.radioButtonPhongKham.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.radioButtonPhongKham.setObjectName("radioButtonPhongKham")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.page)
        self.groupBox_5.setGeometry(QtCore.QRect(670, 430, 401, 131))
        self.groupBox_5.setMaximumSize(QtCore.QSize(410, 150))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Sitka Display\";\n"
"border-radius:10px;\n"
"border: 0.5px solid black;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(10, 90, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;\n"
"")
        self.label_16.setObjectName("label_16")
        self.lineEditThongTin = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lineEditThongTin.setGeometry(QtCore.QRect(130, 80, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditThongTin.setFont(font)
        self.lineEditThongTin.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.lineEditThongTin.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEditThongTin.setObjectName("lineEditThongTin")
        self.comboBoxDichVu = QtWidgets.QComboBox(parent=self.groupBox_5)
        self.comboBoxDichVu.setGeometry(QtCore.QRect(130, 10, 251, 22))
        self.comboBoxDichVu.setStyleSheet("QComboBox {\n"
"    border: none;\n"
"    border-bottom: 1px solid black; \n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    background: transparent;\n"
"    border-radius: 0px;\n"
"}")
        self.comboBoxDichVu.setObjectName("comboBoxDichVu")
        self.lineEditDiaChi = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lineEditDiaChi.setGeometry(QtCore.QRect(130, 40, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditDiaChi.setFont(font)
        self.lineEditDiaChi.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.lineEditDiaChi.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEditDiaChi.setObjectName("lineEditDiaChi")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_17.setObjectName("label_17")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.page)
        self.groupBox_3.setGeometry(QtCore.QRect(670, 570, 401, 91))
        self.groupBox_3.setMaximumSize(QtCore.QSize(410, 150))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Sitka Display\";\n"
"border-radius:10px;\n"
"border: 0.5px solid black;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;\n"
"border: 0px;\n"
"")
        self.label_20.setObjectName("label_20")
        self.lineEditsdtbacsi = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEditsdtbacsi.setGeometry(QtCore.QRect(130, 40, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditsdtbacsi.setFont(font)
        self.lineEditsdtbacsi.setStyleSheet("\n"
"    QLineEdit {\n"
"        border: none;\n"
"        border-bottom: 1px solid black;\n"
"    \n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"        background: transparent;\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.lineEditsdtbacsi.setReadOnly(True)
        self.lineEditsdtbacsi.setObjectName("lineEditsdtbacsi")
        self.comboBoxBacSi = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.comboBoxBacSi.setGeometry(QtCore.QRect(130, 10, 261, 22))
        self.comboBoxBacSi.setStyleSheet("QComboBox {\n"
"    border: none;\n"
"    border-bottom: 1px solid black; \n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    background: transparent;\n"
"    border-radius: 0px;\n"
"}")
        self.comboBoxBacSi.setObjectName("comboBoxBacSi")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.page)
        self.tabWidget.setGeometry(QtCore.QRect(10, 90, 1081, 331))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabLichHen = QtWidgets.QWidget()
        self.tabLichHen.setObjectName("tabLichHen")
        self.tableWidgetThongTinLH = QtWidgets.QTableWidget(parent=self.tabLichHen)
        self.tableWidgetThongTinLH.setGeometry(QtCore.QRect(0, 50, 1071, 251))
        self.tableWidgetThongTinLH.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tableWidgetThongTinLH.setObjectName("tableWidgetThongTinLH")
        self.tableWidgetThongTinLH.setColumnCount(9)
        self.tableWidgetThongTinLH.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinLH.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinLH.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinLH.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinLH.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinLH.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinLH.setHorizontalHeaderItem(8, item)
        self.pushButtonDaXacNhan = QtWidgets.QPushButton(parent=self.tabLichHen)
        self.pushButtonDaXacNhan.setGeometry(QtCore.QRect(360, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonDaXacNhan.setFont(font)
        self.pushButtonDaXacNhan.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-bottom: 2px solid black; \n"
"    \n"
"    background-color: rgb(153, 225, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(39, 154, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(153, 225, 255);\n"
"}")
        self.pushButtonDaXacNhan.setObjectName("pushButtonDaXacNhan")
        self.pushButtonHienThiTatCaLH = QtWidgets.QPushButton(parent=self.tabLichHen)
        self.pushButtonHienThiTatCaLH.setGeometry(QtCore.QRect(220, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonHienThiTatCaLH.setFont(font)
        self.pushButtonHienThiTatCaLH.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #fae38c; \n"
"    border: none; /* Xóa viền */\n"
"    border-bottom: 2px solid black; /* Gạch dưới */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fae38c;\n"
"}\n"
"\n"
"")
        self.pushButtonHienThiTatCaLH.setObjectName("pushButtonHienThiTatCaLH")
        self.pushButtonChuaXacNhan = QtWidgets.QPushButton(parent=self.tabLichHen)
        self.pushButtonChuaXacNhan.setGeometry(QtCore.QRect(500, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonChuaXacNhan.setFont(font)
        self.pushButtonChuaXacNhan.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-bottom: 1.5px solid black; \n"
"    background-color: rgb(255, 108, 98);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(255, 25, 48);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 108, 98);\n"
"}")
        self.pushButtonChuaXacNhan.setObjectName("pushButtonChuaXacNhan")
        self.pushButtonThemLH = QtWidgets.QPushButton(parent=self.tabLichHen)
        self.pushButtonThemLH.setGeometry(QtCore.QRect(20, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonThemLH.setFont(font)
        self.pushButtonThemLH.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #fae38c; \n"
"    border: none; /* Xóa viền */\n"
"    border-bottom: 2px solid black; /* Gạch dưới */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fae38c;\n"
"}\n"
"\n"
"")
        self.pushButtonThemLH.setIconSize(QtCore.QSize(30, 20))
        self.pushButtonThemLH.setObjectName("pushButtonThemLH")
        self.lineEditTimKiem = QtWidgets.QLineEdit(parent=self.tabLichHen)
        self.lineEditTimKiem.setGeometry(QtCore.QRect(730, 10, 251, 31))
        self.lineEditTimKiem.setStyleSheet("QLineEdit {\n"
"    border:1px solid#00007f ;\n"
"    color: rgb(0, 0, 127);\n"
"    border-radius: 15px;        \n"
"    font: 13pt \"MS Shell Dlg 2\";\n"
"    background-color: #fbf9f8;     \n"
"    padding-left: 10px; \n"
"    padding-right: 20px;        \n"
"}")
        self.lineEditTimKiem.setObjectName("lineEditTimKiem")
        self.pushButtonTimKiem = QtWidgets.QPushButton(parent=self.tabLichHen)
        self.pushButtonTimKiem.setGeometry(QtCore.QRect(950, 10, 31, 31))
        self.pushButtonTimKiem.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;                     \n"
"    padding: 5px 10px;        \n"
"    text-decoration: underline;\n"
"    background-color:None;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(208, 209, 208);\n"
"}\n"
"")
        self.pushButtonTimKiem.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/search.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonTimKiem.setIcon(icon)
        self.pushButtonTimKiem.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonTimKiem.setObjectName("pushButtonTimKiem")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../../../../ADMIN/Images/Images_QLLH/hen.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tabLichHen, icon1, "")
        self.tabDK = QtWidgets.QWidget()
        self.tabDK.setObjectName("tabDK")
        self.tableWidgetThongTinDK = QtWidgets.QTableWidget(parent=self.tabDK)
        self.tableWidgetThongTinDK.setGeometry(QtCore.QRect(0, 50, 1071, 251))
        self.tableWidgetThongTinDK.setMaximumSize(QtCore.QSize(1071, 16777215))
        self.tableWidgetThongTinDK.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tableWidgetThongTinDK.setObjectName("tableWidgetThongTinDK")
        self.tableWidgetThongTinDK.setColumnCount(9)
        self.tableWidgetThongTinDK.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinDK.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinDK.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinDK.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinDK.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetThongTinDK.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetThongTinDK.setHorizontalHeaderItem(8, item)
        self.lineEditTimKiemDK = QtWidgets.QLineEdit(parent=self.tabDK)
        self.lineEditTimKiemDK.setGeometry(QtCore.QRect(730, 10, 251, 31))
        self.lineEditTimKiemDK.setStyleSheet("QLineEdit {\n"
"    border:1px solid#00007f ;\n"
"    color: rgb(0, 0, 127);\n"
"    border-radius: 15px;        \n"
"    font: 13pt \"MS Shell Dlg 2\";\n"
"    background-color: #fbf9f8;     \n"
"    padding-left: 10px; \n"
"    padding-right: 20px;        \n"
"}")
        self.lineEditTimKiemDK.setObjectName("lineEditTimKiemDK")
        self.pushButtonTimKiemDK = QtWidgets.QPushButton(parent=self.tabDK)
        self.pushButtonTimKiemDK.setGeometry(QtCore.QRect(950, 10, 31, 31))
        self.pushButtonTimKiemDK.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;                     \n"
"    padding: 5px 10px;        \n"
"    text-decoration: underline;\n"
"    background-color:None;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(208, 209, 208);\n"
"}\n"
"")
        self.pushButtonTimKiemDK.setText("")
        self.pushButtonTimKiemDK.setIcon(icon)
        self.pushButtonTimKiemDK.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonTimKiemDK.setObjectName("pushButtonTimKiemDK")
        self.pushButtonRestore = QtWidgets.QPushButton(parent=self.tabDK)
        self.pushButtonRestore.setGeometry(QtCore.QRect(990, 10, 31, 31))
        self.pushButtonRestore.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;                     \n"
"    padding: 5px 10px;        \n"
"    text-decoration: underline;\n"
"    background-color:None;\n"
"    background-color: rgb(240, 251, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(208, 209, 208);\n"
"}\n"
"")
        self.pushButtonRestore.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/ic_reset.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonRestore.setIcon(icon2)
        self.pushButtonRestore.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonRestore.setObjectName("pushButtonRestore")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../../../../ADMIN/Images/Images_QLLH/dakham (2).ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tabDK, icon3, "")
        self.label_21 = QtWidgets.QLabel(parent=self.page)
        self.label_21.setGeometry(QtCore.QRect(350, 20, 391, 61))
        self.label_21.setStyleSheet("background-color: rgb(52, 76, 183);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px; ")
        self.label_21.setObjectName("label_21")
        self.label = QtWidgets.QLabel(parent=self.page)
        self.label.setGeometry(QtCore.QRect(0, -1, 1100, 701))
        self.label.setStyleSheet("background-color: rgb(218, 241, 249);")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.groupBox_2.raise_()
        self.groupBoxTinhTrang.raise_()
        self.groupBox_6.raise_()
        self.groupBox_5.raise_()
        self.groupBox_3.raise_()
        self.tabWidget.raise_()
        self.label_21.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_3.setGeometry(QtCore.QRect(730, 90, 331, 201))
        self.frame_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(251, 255, 255);\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_25 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/ic_schedule.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_28 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(70, 20, 221, 41))
        self.label_28.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";")
        self.label_28.setObjectName("label_28")
        self.label_34 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_34.setGeometry(QtCore.QRect(30, 130, 261, 51))
        self.label_34.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_34.setObjectName("label_34")
        self.widget_3 = QtWidgets.QWidget(parent=self.frame_3)
        self.widget_3.setGeometry(QtCore.QRect(30, 60, 251, 71))
        self.widget_3.setObjectName("widget_3")
        self.labelTag3 = QtWidgets.QLabel(parent=self.widget_3)
        self.labelTag3.setGeometry(QtCore.QRect(196, 31, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTag3.setFont(font)
        self.labelTag3.setStyleSheet("color: rgb(26, 29, 255);")
        self.labelTag3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelTag3.setObjectName("labelTag3")
        self.labelSoLieu3 = QtWidgets.QLabel(parent=self.widget_3)
        self.labelSoLieu3.setGeometry(QtCore.QRect(0, 0, 181, 71))
        self.labelSoLieu3.setStyleSheet("font: 87 26pt \"Segoe UI Black\";")
        self.labelSoLieu3.setObjectName("labelSoLieu3")
        self.frame_4 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_4.setGeometry(QtCore.QRect(40, 310, 671, 341))
        self.frame_4.setStyleSheet("background-color: rgb(251, 249, 248);\n"
"border-radius:20px;\n"
"background-color: rgb(251, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_35 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_35.setGeometry(QtCore.QRect(70, 10, 401, 41))
        self.label_35.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";\n"
"")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_36.setGeometry(QtCore.QRect(20, 10, 41, 41))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/ic_linechart.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.labelBieuDo = QtWidgets.QLabel(parent=self.frame_4)
        self.labelBieuDo.setGeometry(QtCore.QRect(20, 50, 631, 281))
        self.labelBieuDo.setText("")
        self.labelBieuDo.setScaledContents(True)
        self.labelBieuDo.setObjectName("labelBieuDo")
        self.label_2 = QtWidgets.QLabel(parent=self.page_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1100, 700))
        self.label_2.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame_5 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_5.setGeometry(QtCore.QRect(730, 310, 331, 341))
        self.frame_5.setStyleSheet("background-color: rgb(251, 249, 248);\n"
"border-radius:20px;\n"
"background-color: rgb(251, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_37 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_37.setGeometry(QtCore.QRect(50, 0, 251, 51))
        self.label_37.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";\n"
"")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_38.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/ic_piechart.png"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.labelBDTron = QtWidgets.QLabel(parent=self.frame_5)
        self.labelBDTron.setGeometry(QtCore.QRect(20, 40, 291, 231))
        self.labelBDTron.setText("")
        self.labelBDTron.setScaledContents(True)
        self.labelBDTron.setObjectName("labelBDTron")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(50, 280, 16, 16))
        self.label_3.setStyleSheet("background-color: rgb(107, 200, 247);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(50, 300, 16, 16))
        self.label_4.setStyleSheet("background-color: rgb(250, 227, 140);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(80, 280, 81, 16))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(80, 300, 81, 16))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.frame_1 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_1.setGeometry(QtCore.QRect(40, 90, 321, 201))
        self.frame_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(251, 255, 255);\n"
"")
        self.frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_1.setObjectName("frame_1")
        self.label_23 = QtWidgets.QLabel(parent=self.frame_1)
        self.label_23.setGeometry(QtCore.QRect(70, 20, 151, 41))
        self.label_23.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";\n"
"")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.frame_1)
        self.label_24.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/ic_customer.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_32 = QtWidgets.QLabel(parent=self.frame_1)
        self.label_32.setGeometry(QtCore.QRect(20, 130, 261, 41))
        self.label_32.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_32.setObjectName("label_32")
        self.widget = QtWidgets.QWidget(parent=self.frame_1)
        self.widget.setGeometry(QtCore.QRect(30, 60, 251, 71))
        self.widget.setObjectName("widget")
        self.labelSoLieu1 = QtWidgets.QLabel(parent=self.widget)
        self.labelSoLieu1.setGeometry(QtCore.QRect(0, 0, 181, 71))
        self.labelSoLieu1.setStyleSheet("font: 87 26pt \"Segoe UI Black\";")
        self.labelSoLieu1.setObjectName("labelSoLieu1")
        self.frame_2 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(380, 90, 331, 201))
        self.frame_2.setStyleSheet("background-color: rgb(251, 249, 248);\n"
"background-color: rgb(237, 247, 255);\n"
"border-radius:20px;\n"
"color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_26 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_26.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../Images/Images_QLLH/ic_appointment.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(70, 20, 201, 41))
        self.label_27.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.label_33 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_33.setGeometry(QtCore.QRect(20, 130, 261, 51))
        self.label_33.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_33.setObjectName("label_33")
        self.widget_2 = QtWidgets.QWidget(parent=self.frame_2)
        self.widget_2.setGeometry(QtCore.QRect(20, 60, 281, 71))
        self.widget_2.setObjectName("widget_2")
        self.labelTag2 = QtWidgets.QLabel(parent=self.widget_2)
        self.labelTag2.setGeometry(QtCore.QRect(200, 31, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTag2.setFont(font)
        self.labelTag2.setStyleSheet("color: rgb(26, 29, 255);\n"
"")
        self.labelTag2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelTag2.setObjectName("labelTag2")
        self.labelSoLieu2 = QtWidgets.QLabel(parent=self.widget_2)
        self.labelSoLieu2.setGeometry(QtCore.QRect(10, 0, 171, 71))
        self.labelSoLieu2.setStyleSheet("font: 87 26pt \"Segoe UI Black\";")
        self.labelSoLieu2.setObjectName("labelSoLieu2")
        self.label_22 = QtWidgets.QLabel(parent=self.page_2)
        self.label_22.setGeometry(QtCore.QRect(40, 10, 631, 61))
        self.label_22.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.label_22.setStyleSheet("QLabel {\n"
"    letter-spacing: 5px;\n"
"    font: 26pt \"Roman\";\n"
"    font: 36pt \"PMingLiU-ExtB\";\n"
"    color: rgb(0, 0, 127);\n"
"}")
        self.label_22.setObjectName("label_22")
        self.label_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.frame_1.raise_()
        self.frame_2.raise_()
        self.label_22.raise_()
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuSystem = QtWidgets.QMenu(parent=self.menuBar)
        self.menuSystem.setObjectName("menuSystem")
        self.menuImport_Data = QtWidgets.QMenu(parent=self.menuSystem)
        self.menuImport_Data.setObjectName("menuImport_Data")
        self.menuExport_Data = QtWidgets.QMenu(parent=self.menuSystem)
        self.menuExport_Data.setObjectName("menuExport_Data")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../../../../ADMIN/.designer/images/619539_close_delete_dismiss_exit_cancel_icon (2).ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionText_File = QtGui.QAction(parent=MainWindow)
        self.actionText_File.setObjectName("actionText_File")
        self.actionCSV_File = QtGui.QAction(parent=MainWindow)
        self.actionCSV_File.setObjectName("actionCSV_File")
        self.actionXML_File = QtGui.QAction(parent=MainWindow)
        self.actionXML_File.setObjectName("actionXML_File")
        self.actionJSon_File = QtGui.QAction(parent=MainWindow)
        self.actionJSon_File.setObjectName("actionJSon_File")
        self.actionExcel_File_Import = QtGui.QAction(parent=MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_QuanLyLichHen\\../../../../../ADMIN/.designer/images/2993694_brand_brands_excel_logo_logos_icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExcel_File_Import.setIcon(icon5)
        self.actionExcel_File_Import.setObjectName("actionExcel_File_Import")
        self.actionPickle_File = QtGui.QAction(parent=MainWindow)
        self.actionPickle_File.setObjectName("actionPickle_File")
        self.actionTxt_File = QtGui.QAction(parent=MainWindow)
        self.actionTxt_File.setObjectName("actionTxt_File")
        self.actionCSV_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionCSV_File_2.setObjectName("actionCSV_File_2")
        self.actionJSon_FIle = QtGui.QAction(parent=MainWindow)
        self.actionJSon_FIle.setObjectName("actionJSon_FIle")
        self.actionJSON_File = QtGui.QAction(parent=MainWindow)
        self.actionJSON_File.setObjectName("actionJSON_File")
        self.actionExcel_FIle_Export = QtGui.QAction(parent=MainWindow)
        self.actionExcel_FIle_Export.setIcon(icon5)
        self.actionExcel_FIle_Export.setObjectName("actionExcel_FIle_Export")
        self.actionPickle_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionPickle_File_2.setObjectName("actionPickle_File_2")
        self.actionThongKe = QtGui.QAction(parent=MainWindow)
        self.actionThongKe.setObjectName("actionThongKe")
        self.actionQuayLai = QtGui.QAction(parent=MainWindow)
        self.actionQuayLai.setObjectName("actionQuayLai")
        self.menuImport_Data.addAction(self.actionText_File)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionCSV_File)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionXML_File)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionJSon_File)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionExcel_File_Import)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionPickle_File)
        self.menuExport_Data.addAction(self.actionTxt_File)
        self.menuExport_Data.addSeparator()
        self.menuExport_Data.addAction(self.actionCSV_File_2)
        self.menuExport_Data.addSeparator()
        self.menuExport_Data.addAction(self.actionJSon_FIle)
        self.menuExport_Data.addSeparator()
        self.menuExport_Data.addAction(self.actionJSON_File)
        self.menuExport_Data.addSeparator()
        self.menuExport_Data.addAction(self.actionExcel_FIle_Export)
        self.menuExport_Data.addSeparator()
        self.menuExport_Data.addAction(self.actionPickle_File_2)
        self.menuSystem.addAction(self.actionThongKe)
        self.menuSystem.addAction(self.actionQuayLai)
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.menuImport_Data.menuAction())
        self.menuSystem.addAction(self.menuExport_Data.menuAction())
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.actionExit)
        self.menuBar.addAction(self.menuSystem.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quản lý lịch hẹn - Admin"))
        self.label_10.setText(_translate("MainWindow", "Khách Hàng:"))
        self.label_12.setText(_translate("MainWindow", "Ngày Hẹn:"))
        self.label_13.setText(_translate("MainWindow", "Giờ:"))
        self.label_18.setText(_translate("MainWindow", "Số Điện Thoại:"))
        self.pushButtonLuu.setText(_translate("MainWindow", "Lưu"))
        self.pushButtonXoa.setText(_translate("MainWindow", "Xóa"))
        self.radioButtonDaXacNhan.setText(_translate("MainWindow", "Đã Xác Nhận"))
        self.radioButtonChuaXacNhan.setText(_translate("MainWindow", "Chưa Xác Nhận"))
        self.radioButtonDaKham.setText(_translate("MainWindow", "Đã Khám"))
        self.radioButtonKhamTaiGia.setText(_translate("MainWindow", "Khám Tại Gia"))
        self.radioButtonPhongKham.setText(_translate("MainWindow", "Phòng Khám"))
        self.label_8.setText(_translate("MainWindow", "Dịch Vụ:"))
        self.label_16.setText(_translate("MainWindow", "Thông Tin:"))
        self.label_17.setText(_translate("MainWindow", "Địa Chỉ:"))
        self.label_19.setText(_translate("MainWindow", "Bác sĩ:"))
        self.label_20.setText(_translate("MainWindow", "Số Điện Thoại:"))
        item = self.tableWidgetThongTinLH.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetThongTinLH.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetThongTinLH.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetThongTinLH.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetThongTinLH.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã đơn "))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Họ & Tên"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mã "))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ngày Khám"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Giờ khám"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Dịch Vụ"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Nơi Khám"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Tình Trạng"))
        item = self.tableWidgetThongTinLH.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Bác Sĩ Phụ Trách"))
        self.pushButtonDaXacNhan.setText(_translate("MainWindow", "Đã Xác Nhận"))
        self.pushButtonHienThiTatCaLH.setText(_translate("MainWindow", "Bỏ lọc"))
        self.pushButtonChuaXacNhan.setText(_translate("MainWindow", "Chưa Xác Nhận"))
        self.pushButtonThemLH.setText(_translate("MainWindow", "Thêm Lịch"))
        self.lineEditTimKiem.setPlaceholderText(_translate("MainWindow", "Tìm kiếm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLichHen), _translate("MainWindow", "Lịch Hẹn"))
        item = self.tableWidgetThongTinDK.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetThongTinDK.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetThongTinDK.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetThongTinDK.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetThongTinDK.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã Đơn"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Họ & Tên"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Số Điện Thoại"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ngày Khám"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Giờ khám"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Dịch Vụ"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Nơi Khám"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Tình Trạng"))
        item = self.tableWidgetThongTinDK.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Bác Sĩ Phụ Trách"))
        self.lineEditTimKiemDK.setPlaceholderText(_translate("MainWindow", "Tìm kiếm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDK), _translate("MainWindow", "Đã Khám"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Quản Lý Lịch Hẹn</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">Tổng lịch hẹn trong tuần</span></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-style:italic;\">Tổng số lịch hẹn đã được đặt trong <br/>tuần.</span></p></body></html>"))
        self.labelTag3.setText(_translate("MainWindow", "15%"))
        self.labelSoLieu3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">567</span></p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p>Biểu đồ xu hướng đặt lịch hẹn theo ngày trong tuần</p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p>Tỷ lệ khách hàng mới và quay lại</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Khách Cũ</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Khách Mới</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>Tổng đơn đặt hẹn</p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-style:italic;\">Tổng số đơn khách hàng đã đặt lịch<br/>tại phòng khám.</span></p></body></html>"))
        self.labelSoLieu1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">567</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">Khách đặt lịch hôm nay</span></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-style:italic;\">Số khách hàng có lịch hẹn trong ngày <br/>hôm nay.</span></p></body></html>"))
        self.labelTag2.setText(_translate("MainWindow", "15%"))
        self.labelSoLieu2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">567</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt; font-weight:600;\">DOASHBOARD</span></p></body></html>"))
        self.menuSystem.setTitle(_translate("MainWindow", "Cài Đặt"))
        self.menuImport_Data.setTitle(_translate("MainWindow", "Nhập Dữ Liệu"))
        self.menuExport_Data.setTitle(_translate("MainWindow", "Xuất Dữ Liệu"))
        self.actionExit.setText(_translate("MainWindow", "Đăng Xuất"))
        self.actionText_File.setText(_translate("MainWindow", "Text File"))
        self.actionCSV_File.setText(_translate("MainWindow", "CSV File"))
        self.actionXML_File.setText(_translate("MainWindow", "XML File"))
        self.actionJSon_File.setText(_translate("MainWindow", "JSON File"))
        self.actionExcel_File_Import.setText(_translate("MainWindow", "Excel File"))
        self.actionPickle_File.setText(_translate("MainWindow", "Pickle File"))
        self.actionTxt_File.setText(_translate("MainWindow", "Txt File"))
        self.actionCSV_File_2.setText(_translate("MainWindow", "CSV File"))
        self.actionJSon_FIle.setText(_translate("MainWindow", "XML FIle"))
        self.actionJSON_File.setText(_translate("MainWindow", "JSON File"))
        self.actionExcel_FIle_Export.setText(_translate("MainWindow", "Excel FIle"))
        self.actionPickle_File_2.setText(_translate("MainWindow", "Pickle File"))
        self.actionThongKe.setText(_translate("MainWindow", "Thống Kê"))
        self.actionQuayLai.setText(_translate("MainWindow", "Quay Lại"))
