# Form implementation generated from reading ui file 'D:\DTB\uel\HK1\tu duy lap trinh\DuongThanhBinh_K244060766_Module28\DoAnCuoiKi\Ui\ui_DangNhap\tracuumatkhau.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 700)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 550, 711))
        self.label.setStyleSheet("background-color: rgb(229, 243, 254);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_DangNhap\\../../Images/Images_DangNhap/nen_lay_mk.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 180, 451, 181))
        self.groupBox.setStyleSheet("font: 75 16pt \"Sitka Display\";\n"
"color: rgb(0, 9, 87);\n"
"border: None\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditSearch.setGeometry(QtCore.QRect(10, 50, 421, 51))
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
"    border: 2px;  \n"
"    border-radius: 25px;        \n"
"    font: 14pt \"Sitka Display\";\n"
"    background-color: rgb(232, 231, 231);\n"
"     padding-left: 30px; \n"
"    padding-right: 30px;                \n"
"}")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSearch.setGeometry(QtCore.QRect(320, 120, 101, 41))
        self.pushButtonSearch.setStyleSheet("QPushButton {\n"
"    background-color: #fae38c; \n"
"    border-radius: 15px;       \n"
"    color: black;               \n"
"    padding: 5px 10px;        \n"
"    font: 14pt \"Sitka Display\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fffaba; \n"
"}\n"
"")
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.pushButtonCancel = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonCancel.setGeometry(QtCore.QRect(200, 120, 101, 41))
        self.pushButtonCancel.setStyleSheet("QPushButton {\n"
"    background-color: #fff2c9; \n"
"    border-radius: 15px;       \n"
"    color: black;               \n"
"    padding: 5px 10px;        \n"
"    font: 14pt \"Sitka Display\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeba4a\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fffaba; \n"
"}\n"
"")
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 360, 451, 181))
        self.groupBox_2.setStyleSheet("font: 75 16pt \"Sitka Display\";\n"
"color: rgb(0, 9, 87);\n"
"border: None\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEditTenDangNhap = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditTenDangNhap.setGeometry(QtCore.QRect(20, 40, 401, 51))
        self.lineEditTenDangNhap.setStyleSheet("QLineEdit {\n"
"    border: 2px;  \n"
"    border-radius: 25px;        \n"
"    font: 14pt \"Sitka Display\";\n"
"    background-color: #fbf9f8;     \n"
"    padding-left: 30px; \n"
"    padding-right: 30px;        \n"
"}")
        self.lineEditTenDangNhap.setReadOnly(True)
        self.lineEditTenDangNhap.setObjectName("lineEditTenDangNhap")
        self.lineEditMatKhau = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditMatKhau.setGeometry(QtCore.QRect(20, 110, 401, 51))
        self.lineEditMatKhau.setStyleSheet("QLineEdit {\n"
"    border: 2px;  \n"
"    border-radius: 25px;        \n"
"    font: 14pt \"Sitka Display\";\n"
"    background-color:#fbf9f8;\n"
"     padding-left: 30px; \n"
"    padding-right: 30px;                  \n"
"}")
        self.lineEditMatKhau.setReadOnly(True)
        self.lineEditMatKhau.setObjectName("lineEditMatKhau")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(250, 560, 101, 41))
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(255, 82, 48);\n"
"    border-radius: 15px;       \n"
"    color: black;               \n"
"    padding: 5px 10px;        \n"
"    font: 14pt \"Sitka Display\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 151, 151)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 156, 156); \n"
"}\n"
"")
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">vvffgfhfh</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Vui lòng nhập số điện thoại bạn đã đăng kí:"))
        self.lineEditSearch.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "Nhập số điện thoại "))
        self.pushButtonSearch.setText(_translate("MainWindow", "Tìm kiếm"))
        self.pushButtonCancel.setText(_translate("MainWindow", "Hủy bỏ"))
        self.groupBox_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">vvffgfhfh</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kết Quả:"))
        self.lineEditTenDangNhap.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEditTenDangNhap.setPlaceholderText(_translate("MainWindow", "Tên đăng nhập"))
        self.lineEditMatKhau.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEditMatKhau.setPlaceholderText(_translate("MainWindow", "Mật khẩu "))
        self.pushButtonExit.setText(_translate("MainWindow", "Thoát"))
