# Form implementation generated from reading ui file 'C:\Users\Kieu Tien\DoAnCuoiKy\DoAnCuoiKi\Ui\ui_Qr\qr.ui'
#
<<<<<<< HEAD
# Created by: PyQt6 UI code generator 6.8.1
=======
# Created by: PyQt6 UI code generator 6.7.1
>>>>>>> 0e380858b4dd3a2896515ea5e2320330f20ed309
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 680)
        MainWindow.setMinimumSize(QtCore.QSize(532, 680))
        MainWindow.setMaximumSize(QtCore.QSize(532, 680))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 533, 681))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_Qr\\../../Images/Images_QR/background.jpg"))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 541, 681))
        self.groupBox.setStyleSheet("background-color:None;\n"
"border:None;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(180, 630, 161, 41))
        self.pushButton.setStyleSheet("QPushButton{background-color: rgb(71, 153, 213);\n"
"font: 18pt \"Sitka Display\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"qproperty-wordWrap: true;\n"
"padding:5px;\n"
"font-weight:bold;}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(21, 111, 255);\n"
"color:#000000\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_caution = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_caution.setGeometry(QtCore.QRect(10, 10, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_caution.sizePolicy().hasHeightForWidth())
        self.pushButton_caution.setSizePolicy(sizePolicy)
        self.pushButton_caution.setStyleSheet("QPushButton {background:transparent;\n"
"border:None}\n"
"QPushButton:pressed{background-color: rgb(193, 193, 193);}")
        self.pushButton_caution.setText("")
        icon = QtGui.QIcon()
<<<<<<< HEAD
        icon.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_Qr\\../../Images/Images_DangNhap/ic_back .png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
=======
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Kieu Tien\\DoAnCuoiKy\\DoAnCuoiKi\\Ui\\ui_Qr\\../../Images/Images_DangNhap/ic_back .png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
>>>>>>> 0e380858b4dd3a2896515ea5e2320330f20ed309
        self.pushButton_caution.setIcon(icon)
        self.pushButton_caution.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_caution.setObjectName("pushButton_caution")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thanh Toán"))
        self.pushButton.setText(_translate("MainWindow", "Đăng Nhập"))
