# Form implementation generated from reading ui file 'D:\DTB\uel\HK1\tu duy lap trinh\DuongThanhBinh_K244060766_Module28\DoAnCuoiKi\Ui\ui_QuanLyKhachHang\QLKH.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 730))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 730))
        MainWindow.setStyleSheet("background-color: None;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 1121, 701))
        self.groupBox.setStyleSheet("border:None;\n"
"font: 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 391, 571))
        self.groupBox_2.setStyleSheet("background-color:None;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_caution = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_caution.setGeometry(QtCore.QRect(10, 10, 41, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_caution.sizePolicy().hasHeightForWidth())
        self.pushButton_caution.setSizePolicy(sizePolicy)
        self.pushButton_caution.setStyleSheet("QPushButton:pressed{background-color: rgb(193, 193, 193);}")
        self.pushButton_caution.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_QuanLyKhachHang\\../../Images/Images_QLKH/caution.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_caution.setIcon(icon)
        self.pushButton_caution.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_caution.setObjectName("pushButton_caution")
        self.label_name = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_name.setGeometry(QtCore.QRect(0, 90, 371, 51))
        self.label_name.setStyleSheet("background-color:None;\n"
"font:18pt;")
        self.label_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 141, 31))
        self.label_3.setStyleSheet("font: 16pt \"Sitka Display\";\n"
"background-color:None;")
        self.label_3.setObjectName("label_3")
        self.lineEdit_SDT = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_SDT.setGeometry(QtCore.QRect(150, 140, 221, 41))
        self.lineEdit_SDT.setStyleSheet("background-color: rgb(199, 224, 235);")
        self.lineEdit_SDT.setText("")
        self.lineEdit_SDT.setReadOnly(True)
        self.lineEdit_SDT.setObjectName("lineEdit_SDT")
        self.lineEdit_DiaChi = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_DiaChi.setGeometry(QtCore.QRect(150, 190, 221, 41))
        self.lineEdit_DiaChi.setStyleSheet("background-color: rgb(199, 224, 235);")
        self.lineEdit_DiaChi.setText("")
        self.lineEdit_DiaChi.setObjectName("lineEdit_DiaChi")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 141, 31))
        self.label_4.setStyleSheet("font: 16pt \"Sitka Display\";\n"
"background-color:None;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 240, 141, 31))
        self.label_5.setStyleSheet("font: 16pt \"Sitka Display\";\n"
"background-color:None;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 290, 141, 31))
        self.label_6.setStyleSheet("font: 16pt \"Sitka Display\";\n"
"background-color:None;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 340, 141, 31))
        self.label_7.setStyleSheet("font: 16pt \"Sitka Display\";\n"
"background-color:None;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 390, 141, 31))
        self.label_8.setStyleSheet("font: 16pt \"Sitka Display\";\n"
"background-color:None;")
        self.label_8.setObjectName("label_8")
        self.lineEdit_NoiKham = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_NoiKham.setGeometry(QtCore.QRect(150, 390, 221, 41))
        self.lineEdit_NoiKham.setStyleSheet("background-color: rgb(199, 224, 235);")
        self.lineEdit_NoiKham.setText("")
        self.lineEdit_NoiKham.setObjectName("lineEdit_NoiKham")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 440, 151, 31))
        self.label_9.setStyleSheet("font: 16pt \"Sitka Display\";\n"
"background-color:None;")
        self.label_9.setObjectName("label_9")
        self.lineEdit_ThongTin = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_ThongTin.setGeometry(QtCore.QRect(20, 480, 351, 71))
        self.lineEdit_ThongTin.setStyleSheet("background-color: rgb(199, 224, 235);")
        self.lineEdit_ThongTin.setText("")
        self.lineEdit_ThongTin.setObjectName("lineEdit_ThongTin")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(140, 10, 81, 81))
        self.label.setStyleSheet("background-color:None;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_QuanLyKhachHang\\../../Images/Images_QLKH/avatar.png"))
        self.label.setObjectName("label")
        self.comboBox_DichVuKham = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox_DichVuKham.setGeometry(QtCore.QRect(150, 340, 221, 41))
        self.comboBox_DichVuKham.setStyleSheet("background-color: rgb(199, 224, 235);")
        self.comboBox_DichVuKham.setObjectName("comboBox_DichVuKham")
        self.lineEdit_NgayKham = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_NgayKham.setGeometry(QtCore.QRect(150, 240, 221, 41))
        self.lineEdit_NgayKham.setStyleSheet("background-color: rgb(199, 224, 235);")
        self.lineEdit_NgayKham.setText("")
        self.lineEdit_NgayKham.setReadOnly(True)
        self.lineEdit_NgayKham.setObjectName("lineEdit_NgayKham")
        self.lineEdit_GioKham = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_GioKham.setGeometry(QtCore.QRect(150, 290, 221, 41))
        self.lineEdit_GioKham.setStyleSheet("background-color: rgb(199, 224, 235);")
        self.lineEdit_GioKham.setText("")
        self.lineEdit_GioKham.setReadOnly(True)
        self.lineEdit_GioKham.setObjectName("lineEdit_GioKham")
        self.pushButton_EditName = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_EditName.setGeometry(QtCore.QRect(280, 110, 21, 21))
        self.pushButton_EditName.setStyleSheet("QPushButton:pressed{background-color: rgb(193, 193, 193);}")
        self.pushButton_EditName.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_QuanLyKhachHang\\../../Images/Images_QLKH/edit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_EditName.setIcon(icon1)
        self.pushButton_EditName.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_EditName.setObjectName("pushButton_EditName")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(390, 570, 711, 131))
        self.groupBox_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_Luu = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButton_Luu.setGeometry(QtCore.QRect(40, 40, 191, 51))
        self.pushButton_Luu.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_Luu.setStyleSheet("QPushButton {\n"
"background-color: rgb(148, 197, 219);\n"
"font:  20pt \"Sitka Display Semibold\";\n"
"border-radius:20px;\n"
"border: None;\n"
"    color: rgb(0, 0, 0);\n"
"font-weight:bold;\n"
"padding:5px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(87, 153, 203);\n"
"color:#ffffff;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_QuanLyKhachHang\\../../Images/Images_QLKH/save.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Luu.setIcon(icon2)
        self.pushButton_Luu.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_Luu.setObjectName("pushButton_Luu")
        self.pushButton_DangKyHen = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButton_DangKyHen.setGeometry(QtCore.QRect(260, 40, 191, 51))
        self.pushButton_DangKyHen.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_DangKyHen.setStyleSheet("QPushButton {\n"
"background-color: rgb(148, 197, 219);\n"
"font:  20pt \"Sitka Display Semibold\";\n"
"border-radius:20px;\n"
"border: None;\n"
"    color: rgb(0, 0, 0);\n"
"font-weight:bold;\n"
"padding:5px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(87, 153, 203);\n"
"color:#ffffff;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_QuanLyKhachHang\\../../Images/Images_QLKH/Health.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_DangKyHen.setIcon(icon3)
        self.pushButton_DangKyHen.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_DangKyHen.setObjectName("pushButton_DangKyHen")
        self.pushButton_Xoa = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButton_Xoa.setGeometry(QtCore.QRect(480, 40, 191, 51))
        self.pushButton_Xoa.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_Xoa.setStyleSheet("QPushButton {\n"
"background-color: rgb(148, 197, 219);\n"
"font:  20pt \"Sitka Display Semibold\";\n"
"border-radius:20px;\n"
"border: None;\n"
"    color: rgb(0, 0, 0);\n"
"font-weight:bold;\n"
"padding:5px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(87, 153, 203);\n"
"color:#ffffff;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_QuanLyKhachHang\\../../Images/Images_QLKH/remove.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Xoa.setIcon(icon4)
        self.pushButton_Xoa.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_Xoa.setObjectName("pushButton_Xoa")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 1101, 701))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\DoAnCuoiKi\\Ui\\ui_QuanLyKhachHang\\../../Images/Images_QLKH/background.jpg"))
        self.label_10.setObjectName("label_10")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.groupBox)
        self.scrollArea.setGeometry(QtCore.QRect(400, 100, 681, 461))
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Sitka Display\";\n"
"color: rgb(0, 0, 0);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 681, 461))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.label_10.raise_()
        self.groupBox_2.raise_()
        self.groupBox_5.raise_()
        self.scrollArea.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        self.menuSystem = QtWidgets.QMenu(parent=self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        self.menuImport = QtWidgets.QMenu(parent=self.menuSystem)
        self.menuImport.setObjectName("menuImport")
        self.menuExport = QtWidgets.QMenu(parent=self.menuSystem)
        self.menuExport.setObjectName("menuExport")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionXML_File = QtGui.QAction(parent=MainWindow)
        self.actionXML_File.setObjectName("actionXML_File")
        self.actionJSON_File = QtGui.QAction(parent=MainWindow)
        self.actionJSON_File.setObjectName("actionJSON_File")
        self.actionSheet_File = QtGui.QAction(parent=MainWindow)
        self.actionSheet_File.setObjectName("actionSheet_File")
        self.actionTXT_File = QtGui.QAction(parent=MainWindow)
        self.actionTXT_File.setObjectName("actionTXT_File")
        self.actionCSV_File = QtGui.QAction(parent=MainWindow)
        self.actionCSV_File.setObjectName("actionCSV_File")
        self.actionPICKLE_File = QtGui.QAction(parent=MainWindow)
        self.actionPICKLE_File.setObjectName("actionPICKLE_File")
        self.actionXML_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionXML_File_2.setObjectName("actionXML_File_2")
        self.actionJSON_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionJSON_File_2.setObjectName("actionJSON_File_2")
        self.actionSHEET_File = QtGui.QAction(parent=MainWindow)
        self.actionSHEET_File.setObjectName("actionSHEET_File")
        self.actionTXT_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionTXT_File_2.setObjectName("actionTXT_File_2")
        self.actionCSV_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionCSV_File_2.setObjectName("actionCSV_File_2")
        self.actionPICKLE_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionPICKLE_File_2.setObjectName("actionPICKLE_File_2")
        self.menuImport.addAction(self.actionXML_File)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionJSON_File)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionSheet_File)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionTXT_File)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionCSV_File)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionPICKLE_File)
        self.menuExport.addAction(self.actionXML_File_2)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionJSON_File_2)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionSHEET_File)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionTXT_File_2)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionCSV_File_2)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionPICKLE_File_2)
        self.menuSystem.addAction(self.menuImport.menuAction())
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.menuExport.menuAction())
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.actionExit)
        self.menuSystem.addSeparator()
        self.menubar.addAction(self.menuSystem.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "(Tên Khách Hàng)"))
        self.label_3.setText(_translate("MainWindow", "Số Điện Thoại"))
        self.label_4.setText(_translate("MainWindow", "Địa Chỉ"))
        self.label_5.setText(_translate("MainWindow", "Ngày Khám"))
        self.label_6.setText(_translate("MainWindow", "Giờ Khám"))
        self.label_7.setText(_translate("MainWindow", "Dịch Vụ Khám"))
        self.label_8.setText(_translate("MainWindow", "Nơi Khám"))
        self.label_9.setText(_translate("MainWindow", "Thông tin thêm"))
        self.pushButton_Luu.setText(_translate("MainWindow", "Lưu"))
        self.pushButton_DangKyHen.setText(_translate("MainWindow", "Đăng Ký Hẹn"))
        self.pushButton_Xoa.setText(_translate("MainWindow", "Xóa"))
        self.menuSystem.setTitle(_translate("MainWindow", "System"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionXML_File.setText(_translate("MainWindow", "XML File"))
        self.actionJSON_File.setText(_translate("MainWindow", "JSON File"))
        self.actionSheet_File.setText(_translate("MainWindow", "Sheet File"))
        self.actionTXT_File.setText(_translate("MainWindow", "TXT File"))
        self.actionCSV_File.setText(_translate("MainWindow", "CSV File"))
        self.actionPICKLE_File.setText(_translate("MainWindow", "PICKLE File"))
        self.actionXML_File_2.setText(_translate("MainWindow", "XML File"))
        self.actionJSON_File_2.setText(_translate("MainWindow", "JSON File"))
        self.actionSHEET_File.setText(_translate("MainWindow", "SHEET File"))
        self.actionTXT_File_2.setText(_translate("MainWindow", "TXT File"))
        self.actionCSV_File_2.setText(_translate("MainWindow", "CSV File"))
        self.actionPICKLE_File_2.setText(_translate("MainWindow", "PICKLE File"))
